#pragma once

#ifndef SS_BATTERY_ENABLED
#define SS_BATTERY_ENABLED false
#endif

#ifndef SS_BATTERY_SAMPLE_RATE
#define SS_BATTERY_SAMPLE_RATE 10000
#endif

#ifndef SS_BATTERY_THRESHOLD_PERCENTAGE
#define SS_BATTERY_THRESHOLD_PERCENTAGE 20
#endif

#ifndef SS_BATTERY_TASK_PRIORITY
#define SS_BATTERY_TASK_PRIORITY 1
#endif
