#pragma once

#ifndef SENSESHIFT_BATTERY_ENABLED
#define SENSESHIFT_BATTERY_ENABLED false
#endif

#ifndef SENSESHIFT_BATTERY_SAMPLE_RATE
#define SENSESHIFT_BATTERY_SAMPLE_RATE 10000
#endif

#ifndef SENSESHIFT_BATTERY_THRESHOLD_PERCENTAGE
#define SENSESHIFT_BATTERY_THRESHOLD_PERCENTAGE 20
#endif

#ifndef SENSESHIFT_BATTERY_TASK_PRIORITY
#define SENSESHIFT_BATTERY_TASK_PRIORITY 1
#endif
