#pragma once

#ifndef BATTERY_ENABLED
#define BATTERY_ENABLED false
#endif

#ifndef BATTERY_SAMPLE_RATE
#define BATTERY_SAMPLE_RATE 10000
#endif

#ifndef BATTERY_THRESHOLD_PERCENTAGE
#define BATTERY_THRESHOLD_PERCENTAGE 20
#endif
