#pragma once

#include <BLEUUID.h>

#ifndef BLE_BATTERY_SERVICE_UUID
#define BLE_BATTERY_SERVICE_UUID BLEUUID((uint16_t)0x180F)
#endif

#ifndef BLE_BATTERY_SERVICE_CHAR_LEVEL_UUID
#define BLE_BATTERY_SERVICE_CHAR_LEVEL_UUID BLEUUID((uint16_t)0x2A19)
#endif
