name: Lint

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clang-format:
    name: clang-format - `${{ matrix.path }}`
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'lib'
          - 'include'
          - 'firmware'
          - 'examples'
          - 'test'
          - 'variants'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: '16'
          check-path: ${{ matrix.path }}

  pio-check-cppcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PlatformIO
        uses: ./.github/actions/setup-platformio

      - name: PlatformIO check
        shell: bash
        run: |
          pio check --skip-packages --fail-on-defect=medium --fail-on-defect=high
